### ISSUE TITLE
separate git repos

### ISSUE THREAD

**Issue by oolonek** [commons-research/lotus-structural-expansion#1]
@pamrein great to have a look at this first git repo.

I guess you could split it in two repos here. One per task.

- the first one to have some script for the building of a subset of LOTUS
- tests regarding interaction with the MINE API can be in another one

**Comment by pamrein** [comment]
I created a new Repo ["Mine-Search"](https://github.com/commons-research/MINE-Search.git).
Do I understand correctly, that also the "subset buildener of LOTUS" should be moved in a seperated repo?
This repo here would be for the final. The other two repos would be linked from this repo?

@oolonek Should I move the "toydataset script" also in a new repo?

**Comment by pamrein** [comment]
Ok, I had some good excercise to move/create repos.

Here is the other one: [lotus dataset](git@github.com:commons-research/dataset-extractor-lotus.git)

**Comment by pamrein** [comment]
https://github.com/commons-research/dataset-extractor-lotus.git
